### ISSUE TITLE
Cache paged APIs

### ISSUE THREAD

**Issue by danfascia** [11ty/eleventy-fetch#2]
How can you use this plugin to cache JSON from an API that requires paging i.e. several calls to gather all of the data before committing it to cache?

**Comment by jeromecoupe** [comment]
@danfascia I recently used flat-cache for that. Saving the results of the several calls to cache. Here is some sample code for the general structure. I generally clean the cache folder at build time.

```js
const path = require("path");
const flatCache = require("flat-cache");
const cacheFolder = path.resolve("./_datacache");

// get blogposts
async function getBlogposts() {
  // load cache
  let cache = flatCache.load("blogposts.json", cacheFolder);
  const cachedItems = cache.getKey("items");

  // if we have a cache, return cached data
  if (cachedItems) {
    console.log("Blogposts from cache");
    // return cached data
    return cachedItems;
  }

  // if we don't have a cache, make queries
  
  // empty array to save data
  let allItems = [];
  
  // ***
  // multiple queries in some kind of loop
  // push to allItems for each batch of results
  // ***

  // set and save cache
  cache.setKey("items", allItems);
  cache.save(true);

  // return API data
  return allItems;
}

module.exports = getBlogposts;
```

**Comment by zachleat** [comment]
> This repository is now using [lodash style issue management](https://twitter.com/samselikoff/status/991395669016436736) for enhancements. This means enhancement issues will now be closed instead of leaving them open.

> View [the enhancement backlog here](https://github.com/11ty/eleventy-fetch/issues?utf8=%E2%9C%93&q=label%3Aneeds-votes+sort%3Areactions-%2B1-desc+). Don’t forget to upvote the top comment with 👍!

**Comment by zachleat** [comment]
Moving this one into the enhancement queue
