### ISSUE TITLE
Allow using GitHub access token or oauth to surpass api.github.com ratelimits

### ISSUE THREAD

**Issue by txtsd** [11ty/eleventy-fetch#30]
We've been getting [403 Rate Limit Exceeded on our builds](https://app.netlify.com/sites/prismlauncher/deploys/6417488c82a8580008e3e4bc#L74), and this would be a great new feature.

**Comment by pdehaan** [comment]
@txtsd it's been a while since I've played w/ the GitHub API, but does it [still?] support setting the GITHUB_TOKEN as an env var, and would that work for you here?

**Comment by txtsd** [comment]
> @txtsd it's been a while since I've played w/ the GitHub API, but does it [still?] support setting the GITHUB_TOKEN as an env var, and would that work for you here?

That only works from within GitHub Actions, afaik.

**Comment by pdehaan** [comment]
Ah, I think I've mostly used the npm [@octokit/rest](https://www.npmjs.com/package/@octokit/rest) package when playing w/ the GitHub API and could set my `auth` token in there from an env var, per https://octokit.github.io/rest.js/v19#authentication.

Also found https://docs.github.com/en/rest/rate-limit which also recommends Octokit if you're using JavaScript.

https://www.11ty.dev/docs/plugins/fetch/#fetch-google-fonts-css has an example of passing custom HTTP headers. And the above [rate limit](https://docs.github.com/en/rest/rate-limit) link shows setting a custom bearer token in the cURL example: `-H "Authorization: Bearer <YOUR-TOKEN>"\`. Wonder if a combination of that sorcery might work. 🤔

**Comment by pdehaan** [comment]
So this cURL will show your API rate limit status:

```sh
curl -L \
  -H "Accept: application/vnd.github+json" \
  https://api.github.com/rate_limit

{
  "resources": {
    ...
  },
  "rate": {
    "limit": 60,
    "remaining": 52,
    "reset": 1679368640,
    "used": 8,
    "resource": "core"
  }
}
```

Now I guess the question is generating a GitHub auth token and trying to explicitly set the `"Authorization: Bearer <YOUR-TOKEN>"` header and see if those authenticated requests count against your quota.

**Comment by zachleat** [comment]
This is supported, example here:

https://github.com/11ty/11ty-website/blob/342721d5369dc7108f15562cff5ee56ce9d89917/config/activity.js#L31-L32
