### ISSUE TITLE
Add more debug output to AssetCache

### ISSUE THREAD

**Issue by clottman** [11ty/eleventy-fetch#31]
When manually storing data in the cache ([example from site](https://www.11ty.dev/docs/plugins/fetch/#manually-store-your-own-data-in-the-cache), if you don't call `asset.isCacheValid()` and aren't using any other Eleventy-Fetch code, running in debug mode won't show any output at all from the Eleventy Fetch plugin.

This makes it hard to know if your asset cache is working and if not, why. 

Things that I'd love to have included in the verbose/debug output: 
 - writing to a particular cache (`asset.save` called)
 - retrieved cached value (`asset.getCachedValue()` called) 
 - file path that caches are being stored in

**Comment by zachleat** [comment]
Shipping with v4.0.1
