### ISSUE TITLE
Ability to cache response.headers

### ISSUE THREAD

**Issue by swaroopsm** [11ty/eleventy-fetch#4]
Thank you for this library 👍. I use `RemoteAssetCache` alongside with one of my `11ty` projects in development mode to cache few requests to a wordpress backend.

In addition to caching `response.body`, is there a way to also cache `response.headers`.
I am currently querying the wordpress backend via REST API and wordpress returns the total posts via a header `x-wp-totalpages` which I then use to make additional api requests until I get the entire list of posts and `11ty` can build it out.

How about an extra option like: `options.getResponseValue` or `options.beforeSave` be exposed in order to modify the response before storing it in the cache?

**Comment by schneyra** [comment]
This is funny. I'm having the exact same problem.

**Comment by michaelkostal** [comment]
+1

**Comment by zachleat** [comment]
Putting this one into the enhancement queue

> This repository is now using [lodash style issue management](https://twitter.com/samselikoff/status/991395669016436736) for enhancements. This means enhancement issues will now be closed instead of leaving them open.

> View [the enhancement backlog here](https://github.com/11ty/eleventy-fetch/issues?utf8=%E2%9C%93&q=label%3Aneeds-votes+sort%3Areactions-%2B1-desc+). Don’t forget to upvote the top comment with 👍!

**Comment by groenroos** [comment]
+1 for this feature - with no access to response headers, loading data from any WordPress REST API (i.e. any headless WP setup where Eleventy would serve the frontend) is not possible.

#25 has a workaround, but it involves basically writing your own fetcher from scratch - the later examples appear to skip involving `EleventyFetch` altogether.

More widely, perhaps some sort of built-in pagination handling might be nice; or even exposing a config key for a method for determining whether/how another page should be loaded. For me, 100/100 times when I load data with `EleventyFetch`, I want every single page available.

Maybe something like so (semi-pseudo code):

```js
const data = await fetch("wordpress/wp-json/wp/v2/stuff", {
	duration: '0s',
	type: 'json',
	nextPage(request, response, index, next) {
		if (response.headers['x-wp-totalpages'] < index) {
			next(`${request.url}?page=${index + 1}`);
		} else {
			return false;
		}
	}
});
```
