### ISSUE TITLE
My website has a lot of requests, and when the cache directory is large, the program will be slow

### ISSUE THREAD

**Issue by chaegumi** [11ty/eleventy-fetch#48]
I use Astro and I have a website with over 7000 pages, so my website has a lot of requests. When the cache directory is large, the program will be slow

The cache directory has over 300 MB and 40000 cache files

**Comment by chaegumi** [comment]
When the cache directory is too large and there are too many files, there may be problems. You can learn how to use `cacache` to save in separate directories

**Comment by zachleat** [comment]
We don’t have the bandwidth to provide support for Astro projects, sorry!

**Comment by chaegumi** [comment]
It's not related to any framework, there are problems when there are too many generated cache files



---Original---
From: "Zach ***@***.***&gt;
Date: Tue, Oct 22, 2024 21:18 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [11ty/eleventy-fetch] My website has a lot of requests, and whenthe cache directory is large, the program will be slow (Issue #48)




 
We don’t have the bandwidth to provide support for Astro projects, sorry!
