### ISSUE TITLE
Can this plugin be used with Axios together?

### ISSUE THREAD

**Issue by winston0410** [11ty/eleventy-fetch#5]
Can this plugin be used with Axios together?  Is there any example I can set this up properly?

**Comment by zachleat** [comment]
I think it would be awesome to pull out the fetching code to allow adapters here, especially since Node is getting first class fetch.

**Comment by zachleat** [comment]
> This repository is now using [lodash style issue management](https://twitter.com/samselikoff/status/991395669016436736) for enhancements. This means enhancement issues will now be closed instead of leaving them open.

> View [the enhancement backlog here](https://github.com/11ty/eleventy-fetch/issues?utf8=%E2%9C%93&q=label%3Aneeds-votes+sort%3Areactions-%2B1-desc+). Don’t forget to upvote the top comment with 👍!

**Comment by zachleat** [comment]
Removing this one from the enhancement queue.
